package com.eps_hioa_2013.JointAttentionResearchApp;



import android.app.ListActivity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.support.v4.app.NavUtils;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.TextView;

public class ModuleActivity extends ListActivity {
	private Session mysession;

	//receives the sessionobject and saves it into mysession
	//+ sets the input in the overview of the top of the screen
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_module);
		// Show the Up button in the action bar.
		setupActionBar();
		
		Intent intent = getIntent();
		mysession = this.fillSession(intent);
				
		setupModuleList(); //for the list 
	}
	
	protected void onResume() {
		//getting last 4 saved modules
		TextView textView10 = (TextView) findViewById(R.id.lastused_textview);
		textView10.setText(this.getNameOfModule("0"));
		TextView textView11 = (TextView) findViewById(R.id.lastused_textview2);
		textView11.setText(this.getNameOfModule("1"));
		TextView textView12 = (TextView) findViewById(R.id.lastused_textview3);
		textView12.setText(this.getNameOfModule("2"));		
		TextView textView13 = (TextView) findViewById(R.id.lastused_textview4);
		textView13.setText(this.getNameOfModule("3"));
  
		super.onResume();
	}
	
	//fills a Session-Object with the details delivered by the user in Activty_module screen
	Session fillSession(Intent intent)
	{
		mysession = (Session) intent.getSerializableExtra(MainActivity.EXTRA_SESSION);
		// Create the text view
		TextView textView = (TextView) findViewById(R.id.password_textview);
		textView.setText(mysession.getPassword());
		
		TextView textView2 = (TextView) findViewById(R.id.participant_textview);
		textView2.setText(mysession.getParticipant());

		TextView textView3 = (TextView) findViewById(R.id.researcher_textview);
		textView3.setText(mysession.getResearcher());
		
		TextView textView4 = (TextView) findViewById(R.id.date_textview);
		textView4.setText(mysession.getcurrentDate().toString());
		
		return mysession;
	}
	
	//gets module_name out of the last edited module
	String getNameOfLastEditedModule()
	{	
		SharedPreferences pref_modulecounter = getSharedPreferences("counter", 0); 
        int modulecounter = pref_modulecounter.getInt("modulecounter", 0);
        
		String nameOfModulePref = "MODULE" + modulecounter;
    	SharedPreferences pref_modulesettings = getSharedPreferences(nameOfModulePref, 0);  
        String lastEditedModule = pref_modulesettings.getString("module_name", ACCESSIBILITY_SERVICE);
		return lastEditedModule;				
	}
	
	//gets module_name out of the module i
	String getNameOfModule(String i)
	{	
		String nameOfModulePref = "MODULE" + i;
    	SharedPreferences pref_modulesettings = getSharedPreferences(nameOfModulePref, 0);  
        String nameOfModule = pref_modulesettings.getString("module_name", ACCESSIBILITY_SERVICE);
		return nameOfModule;
				
	}
	
	//sets the modulecounter to -1. When a new module gets added, it has the number 0
	//this Method is also present in ModuleSettingsActivity.java; This should be solved in a better way
	public void onclick_reset_modulecounter(View view)
	{
    	SharedPreferences pref_modulecounter = getSharedPreferences("counter", 0);
        SharedPreferences.Editor editor = pref_modulecounter.edit();
        int count = -1;
        editor.putInt("modulecounter", count);
        editor.commit();
	}
	
	
	
	
	
	//shows the Modulesettings-screen for setting up a new module
	public void onclick_add_module(View view)
	{
		
		Intent intent = new Intent(this, ModuleSettingsActivity.class);
		startActivity(intent);
		
	}
	

	
	
	//for testing	
	//creates the list out of the modules.xml 05.10.13
	public void setupModuleList()
	{
		ArrayAdapter<String> adapter = new ArrayAdapter<String>(
				this,
				android.R.layout.simple_list_item_1,
				getResources().getStringArray(R.array.fruits));
		
		setListAdapter(adapter);
	}

	/**
	 * Set up the {@link android.app.ActionBar}.
	 */
	//Autogenerated, dont know
	private void setupActionBar() {

		getActionBar().setDisplayHomeAsUpEnabled(true);

	}

	//Autogenerated, dont know
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.module, menu);
		return true;
	}

	//Autogenerated, dont know
	public boolean onOptionsItemSelected(MenuItem item) {
		switch (item.getItemId()) {
		case android.R.id.home:
			// This ID represents the Home or Up button. In the case of this
			// activity, the Up button is shown. Use NavUtils to allow users
			// to navigate up one level in the application structure. For
			// more details, see the Navigation pattern on Android Design:
			//
			// http://developer.android.com/design/patterns/navigation.html#up-vs-back
			//
			NavUtils.navigateUpFromSameTask(this);
			return true;
		}
		return super.onOptionsItemSelected(item);
	}

}
